#!/usr/bin/env python3
"""
Auto-generated integration tests from 環境省通知PDF法令参照.
Source: 120 PDFs from https://www.env.go.jp/hourei/add/index.html
Generated: 445 unique law article references extracted via pdfplumber.

These tests verify that the MCP server can correctly retrieve every
law article referenced in official Ministry of Environment notifications.

Requires: disk cache populated (run env_mcp_verify.py first) or internet access.
"""
import asyncio
import json
import re
import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from mcp_server import (
    smart_law_lookup,
    find_article_in_xml,
    extract_text_from_xml,
    generate_search_patterns,
    get_http_client,
    cache_manager,
    LAW_ALIASES,
    BASIC_LAWS,
)
import json as json_mod
import re as re_mod


async def _find_article(law_name, article, paragraph=None, item=None):
    """Minimal find_law_article for testing (avoids cli.py stdout override)."""
    if law_name.strip() in LAW_ALIASES:
        law_name = LAW_ALIASES[law_name.strip()]
    law_num = await smart_law_lookup(law_name)
    if not law_num:
        return {"error": f"Law '{law_name}' not found"}

    cached = cache_manager.law_content_cache.get(law_num)
    if cached:
        data = cached
    else:
        disk = cache_manager.disk_cache.get(f"law_data:{law_num}")
        if disk:
            data = disk
            cache_manager.law_content_cache.put(law_num, data)
        else:
            async with await get_http_client() as client:
                resp = await client.get(f"/law_data/{law_num}", params={"law_full_text_format": "xml"})
                resp.raise_for_status()
                data = json_mod.loads(resp.text)
                cache_manager.law_content_cache.put(law_num, data)
                cache_manager.disk_cache.put(f"law_data:{law_num}", data)

    law_full_text = data.get("law_full_text", {})
    # Primary: XML structure
    matches = find_article_in_xml(law_full_text, article,
                                   paragraph=paragraph, item=item)
    if matches:
        return {"matches_found": len(matches)}
    # Fallback: regex on extracted text
    text = extract_text_from_xml(law_full_text)
    patterns = generate_search_patterns(article)
    for p in patterns:
        if re_mod.search(re_mod.escape(p), text):
            return {"matches_found": 1}
    return {"matches_found": 0}


ENV_PDF_PARAMS = [
    pytest.param("廃棄物処理法", "5_2", "", "", id="廃棄物処理法_art5_2"),
    pytest.param("廃棄物処理法", "7", "1", "", id="廃棄物処理法_art7_p1"),
    pytest.param("廃棄物処理法", "6", "", "", id="廃棄物処理法_art6"),
    pytest.param("廃棄物処理法", "6", "1", "", id="廃棄物処理法_art6_p1"),
    pytest.param("廃棄物処理法", "8", "", "", id="廃棄物処理法_art8"),
    pytest.param("廃棄物処理法", "16", "", "", id="廃棄物処理法_art16"),
    pytest.param("廃棄物処理法", "17", "", "", id="廃棄物処理法_art17"),
    pytest.param("廃棄物処理法", "9", "2", "", id="廃棄物処理法_art9_p2"),
    pytest.param("廃棄物処理法", "5", "", "", id="廃棄物処理法_art5"),
    pytest.param("廃棄物処理法", "2", "3", "", id="廃棄物処理法_art2_p3"),
    pytest.param("廃棄物処理法", "10", "", "", id="廃棄物処理法_art10"),
    pytest.param("廃棄物処理法", "3", "", "", id="廃棄物処理法_art3"),
    pytest.param("廃棄物処理法", "3", "1", "", id="廃棄物処理法_art3_p1"),
    pytest.param("廃棄物処理法施行規則", "15", "2", "1", id="廃棄物処理法施行規則_art15_p2_i1"),
    pytest.param("廃棄物処理法施行令", "12", "", "", id="廃棄物処理法施行令_art12"),
    pytest.param("廃棄物処理法施行令", "13", "1", "", id="廃棄物処理法施行令_art13_p1"),
    pytest.param("廃棄物処理法", "18_15", "1", "", id="廃棄物処理法_art18_15_p1"),
    pytest.param("廃棄物処理法", "26", "", "", id="廃棄物処理法_art26"),
    pytest.param("廃棄物処理法", "18_17", "", "", id="廃棄物処理法_art18_17"),
    pytest.param("廃棄物処理法", "18_18", "", "", id="廃棄物処理法_art18_18"),
    pytest.param("廃棄物処理法施行規則", "13", "4", "", id="廃棄物処理法施行規則_art13_p4"),
    pytest.param("廃棄物処理法施行令", "13", "", "", id="廃棄物処理法施行令_art13"),
    pytest.param("廃棄物処理法", "22", "", "", id="廃棄物処理法_art22"),
    pytest.param("廃棄物処理法施行規則", "1_3", "1", "2", id="廃棄物処理法施行規則_art1_3_p1_i2"),
    pytest.param("廃棄物処理法施行令", "2", "", "", id="廃棄物処理法施行令_art2"),
    pytest.param("廃棄物処理法施行令", "2", "", "1", id="廃棄物処理法施行令_art2_i1"),
    pytest.param("廃棄物処理法", "15", "", "", id="廃棄物処理法_art15"),
    pytest.param("廃棄物処理法", "16", "2", "", id="廃棄物処理法_art16_p2"),
    pytest.param("廃棄物処理法施行令", "2", "2", "15", id="廃棄物処理法施行令_art2_p2_i15"),
    pytest.param("廃棄物処理法施行令", "2", "2", "17", id="廃棄物処理法施行令_art2_p2_i17"),
    pytest.param("廃棄物処理法施行令", "2", "2", "13", id="廃棄物処理法施行令_art2_p2_i13"),
    pytest.param("廃棄物処理法施行令", "4", "", "1", id="廃棄物処理法施行令_art4_i1"),
    pytest.param("廃棄物処理法施行令", "5", "", "4", id="廃棄物処理法施行令_art5_i4"),
    pytest.param("廃棄物処理法施行令", "5", "", "17", id="廃棄物処理法施行令_art5_i17"),
    pytest.param("廃棄物処理法施行令", "14", "1", "2", id="廃棄物処理法施行令_art14_p1_i2"),
    pytest.param("廃棄物処理法施行令", "14", "1", "3", id="廃棄物処理法施行令_art14_p1_i3"),
    pytest.param("廃棄物処理法施行令", "14", "1", "4", id="廃棄物処理法施行令_art14_p1_i4"),
    pytest.param("廃棄物処理法施行令", "14", "1", "6", id="廃棄物処理法施行令_art14_p1_i6"),
    pytest.param("廃棄物処理法施行令", "15", "1", "2", id="廃棄物処理法施行令_art15_p1_i2"),
    pytest.param("廃棄物処理法施行令", "15", "1", "3", id="廃棄物処理法施行令_art15_p1_i3"),
    pytest.param("廃棄物処理法施行令", "15", "1", "4", id="廃棄物処理法施行令_art15_p1_i4"),
    pytest.param("廃棄物処理法施行令", "15", "1", "5", id="廃棄物処理法施行令_art15_p1_i5"),
    pytest.param("廃棄物処理法施行令", "15", "1", "6", id="廃棄物処理法施行令_art15_p1_i6"),
    pytest.param("廃棄物処理法施行令", "15", "1", "7", id="廃棄物処理法施行令_art15_p1_i7"),
    pytest.param("廃棄物処理法施行令", "15", "2", "", id="廃棄物処理法施行令_art15_p2"),
    pytest.param("廃棄物処理法施行令", "16", "1", "4", id="廃棄物処理法施行令_art16_p1_i4"),
    pytest.param("廃棄物処理法施行令", "16", "1", "5", id="廃棄物処理法施行令_art16_p1_i5"),
    pytest.param("廃棄物処理法施行令", "16", "1", "6", id="廃棄物処理法施行令_art16_p1_i6"),
    pytest.param("廃棄物処理法施行令", "16", "1", "7", id="廃棄物処理法施行令_art16_p1_i7"),
    pytest.param("廃棄物処理法施行令", "16", "2", "", id="廃棄物処理法施行令_art16_p2"),
    pytest.param("廃棄物処理法", "1", "", "", id="廃棄物処理法_art1"),
    pytest.param("廃棄物処理法", "22", "3", "2", id="廃棄物処理法_art22_p3_i2"),
    pytest.param("廃棄物処理法", "22", "1", "", id="廃棄物処理法_art22_p1"),
    pytest.param("廃棄物処理法", "23", "1", "", id="廃棄物処理法_art23_p1"),
    pytest.param("廃棄物処理法", "27_2", "", "", id="廃棄物処理法_art27_2"),
    pytest.param("廃棄物処理法", "22", "4", "", id="廃棄物処理法_art22_p4"),
    pytest.param("廃棄物処理法施行令", "3", "", "1", id="廃棄物処理法施行令_art3_i1"),
    pytest.param("廃棄物処理法施行令", "8", "", "", id="廃棄物処理法施行令_art8"),
    pytest.param("廃棄物処理法施行令", "1", "", "", id="廃棄物処理法施行令_art1"),
    pytest.param("廃棄物処理法施行令", "3", "", "3", id="廃棄物処理法施行令_art3_i3"),
    pytest.param("廃棄物処理法施行令", "3", "", "5", id="廃棄物処理法施行令_art3_i5"),
    pytest.param("廃棄物処理法施行令", "2", "2", "2", id="廃棄物処理法施行令_art2_p2_i2"),
    pytest.param("廃棄物処理法施行令", "3", "", "7", id="廃棄物処理法施行令_art3_i7"),
    pytest.param("廃棄物処理法施行令", "5", "", "22", id="廃棄物処理法施行令_art5_i22"),
    pytest.param("廃棄物処理法施行令", "2", "2", "3", id="廃棄物処理法施行令_art2_p2_i3"),
    pytest.param("廃棄物処理法施行令", "2", "2", "4", id="廃棄物処理法施行令_art2_p2_i4"),
    pytest.param("廃棄物処理法施行令", "2", "2", "", id="廃棄物処理法施行令_art2_p2"),
    pytest.param("廃棄物処理法施行令", "4", "", "2", id="廃棄物処理法施行令_art4_i2"),
    pytest.param("廃棄物処理法施行令", "2", "2", "9", id="廃棄物処理法施行令_art2_p2_i9"),
    pytest.param("廃棄物処理法施行令", "2", "2", "14", id="廃棄物処理法施行令_art2_p2_i14"),
    pytest.param("廃棄物処理法施行令", "2", "2", "16", id="廃棄物処理法施行令_art2_p2_i16"),
    pytest.param("廃棄物処理法施行令", "2", "2", "19", id="廃棄物処理法施行令_art2_p2_i19"),
    pytest.param("廃棄物処理法施行令", "2", "2", "20", id="廃棄物処理法施行令_art2_p2_i20"),
    pytest.param("廃棄物処理法施行令", "2", "2", "21", id="廃棄物処理法施行令_art2_p2_i21"),
    pytest.param("廃棄物処理法施行令", "14", "1", "", id="廃棄物処理法施行令_art14_p1"),
    pytest.param("廃棄物処理法施行令", "4", "", "", id="廃棄物処理法施行令_art4"),
    pytest.param("廃棄物処理法施行令", "10", "", "1", id="廃棄物処理法施行令_art10_i1"),
    pytest.param("廃棄物処理法施行令", "5", "", "", id="廃棄物処理法施行令_art5"),
    pytest.param("廃棄物処理法施行令", "5", "", "1", id="廃棄物処理法施行令_art5_i1"),
    pytest.param("廃棄物処理法施行令", "5", "", "2", id="廃棄物処理法施行令_art5_i2"),
    pytest.param("廃棄物処理法施行令", "5", "", "3", id="廃棄物処理法施行令_art5_i3"),
    pytest.param("廃棄物処理法施行令", "5", "1", "", id="廃棄物処理法施行令_art5_p1"),
    pytest.param("廃棄物処理法施行令", "5", "2", "", id="廃棄物処理法施行令_art5_p2"),
    pytest.param("廃棄物処理法施行令", "1", "2", "", id="廃棄物処理法施行令_art1_p2"),
    pytest.param("廃棄物処理法施行令", "5", "", "5", id="廃棄物処理法施行令_art5_i5"),
    pytest.param("廃棄物処理法施行令", "5", "", "8", id="廃棄物処理法施行令_art5_i8"),
    pytest.param("廃棄物処理法施行令", "5", "", "9", id="廃棄物処理法施行令_art5_i9"),
    pytest.param("廃棄物処理法施行令", "5", "", "11", id="廃棄物処理法施行令_art5_i11"),
    pytest.param("廃棄物処理法施行令", "5", "", "12", id="廃棄物処理法施行令_art5_i12"),
    pytest.param("廃棄物処理法施行令", "5", "", "13", id="廃棄物処理法施行令_art5_i13"),
    pytest.param("廃棄物処理法施行令", "5", "", "15", id="廃棄物処理法施行令_art5_i15"),
    pytest.param("廃棄物処理法施行令", "5", "", "16", id="廃棄物処理法施行令_art5_i16"),
    pytest.param("廃棄物処理法施行令", "5", "", "18", id="廃棄物処理法施行令_art5_i18"),
    pytest.param("廃棄物処理法施行令", "5", "", "19", id="廃棄物処理法施行令_art5_i19"),
    pytest.param("廃棄物処理法施行令", "5", "", "20", id="廃棄物処理法施行令_art5_i20"),
    pytest.param("廃棄物処理法施行令", "5", "", "21", id="廃棄物処理法施行令_art5_i21"),
    pytest.param("廃棄物処理法施行令", "5", "", "23", id="廃棄物処理法施行令_art5_i23"),
    pytest.param("廃棄物処理法", "22", "2", "2", id="廃棄物処理法_art22_p2_i2"),
    pytest.param("廃棄物処理法", "22", "2", "3", id="廃棄物処理法_art22_p2_i3"),
    pytest.param("廃棄物処理法", "22", "2", "4", id="廃棄物処理法_art22_p2_i4"),
    pytest.param("廃棄物処理法", "27", "1", "", id="廃棄物処理法_art27_p1"),
    pytest.param("廃棄物処理法", "23", "3", "", id="廃棄物処理法_art23_p3"),
    pytest.param("廃棄物処理法", "22", "2", "", id="廃棄物処理法_art22_p2"),
    pytest.param("廃棄物処理法", "25", "", "", id="廃棄物処理法_art25"),
    pytest.param("廃棄物処理法", "8_5", "1", "", id="廃棄物処理法_art8_5_p1"),
    pytest.param("廃棄物処理法", "25", "", "1", id="廃棄物処理法_art25_i1"),
    pytest.param("廃棄物処理法", "22", "6", "", id="廃棄物処理法_art22_p6"),
    pytest.param("廃棄物処理法", "22", "9", "", id="廃棄物処理法_art22_p9"),
    pytest.param("廃棄物処理法", "20", "1", "", id="廃棄物処理法_art20_p1"),
    pytest.param("廃棄物処理法", "20", "4", "", id="廃棄物処理法_art20_p4"),
    pytest.param("廃棄物処理法", "20", "", "", id="廃棄物処理法_art20"),
    pytest.param("廃棄物処理法施行規則", "6", "2", "2", id="廃棄物処理法施行規則_art6_p2_i2"),
    pytest.param("廃棄物処理法", "11_2", "", "", id="廃棄物処理法_art11_2"),
    pytest.param("廃棄物処理法", "11_2", "1", "", id="廃棄物処理法_art11_2_p1"),
    pytest.param("廃棄物処理法", "5", "2", "2", id="廃棄物処理法_art5_p2_i2"),
    pytest.param("廃棄物処理法", "18", "", "", id="廃棄物処理法_art18"),
    pytest.param("廃棄物処理法", "7", "", "", id="廃棄物処理法_art7"),
    pytest.param("廃棄物処理法", "2", "4", "", id="廃棄物処理法_art2_p4"),
    pytest.param("廃棄物処理法", "4", "1", "", id="廃棄物処理法_art4_p1"),
    pytest.param("廃棄物処理法", "4", "2", "", id="廃棄物処理法_art4_p2"),
    pytest.param("廃棄物処理法", "2", "2", "", id="廃棄物処理法_art2_p2"),
    pytest.param("廃棄物処理法", "3", "3", "", id="廃棄物処理法_art3_p3"),
    pytest.param("廃棄物処理法", "8", "1", "", id="廃棄物処理法_art8_p1"),
    pytest.param("廃棄物処理法", "8", "2", "", id="廃棄物処理法_art8_p2"),
    pytest.param("廃棄物処理法", "12", "5", "", id="廃棄物処理法_art12_p5"),
    pytest.param("廃棄物処理法", "10", "1", "", id="廃棄物処理法_art10_p1"),
    pytest.param("廃棄物処理法", "10", "2", "", id="廃棄物処理法_art10_p2"),
    pytest.param("廃棄物処理法", "2", "", "1", id="廃棄物処理法_art2_i1"),
    pytest.param("廃棄物処理法", "3", "", "8", id="廃棄物処理法_art3_i8"),
    pytest.param("廃棄物処理法施行規則", "8", "", "", id="廃棄物処理法施行規則_art8"),
    pytest.param("廃棄物処理法施行規則", "9", "1", "", id="廃棄物処理法施行規則_art9_p1"),
    pytest.param("廃棄物処理法施行規則", "9", "", "", id="廃棄物処理法施行規則_art9"),
    pytest.param("廃棄物処理法施行令", "2", "1", "", id="廃棄物処理法施行令_art2_p1"),
    pytest.param("廃棄物処理法", "2", "", "4", id="廃棄物処理法_art2_i4"),
    pytest.param("廃棄物処理法", "13", "", "", id="廃棄物処理法_art13"),
    pytest.param("廃棄物処理法", "7", "6", "", id="廃棄物処理法_art7_p6"),
    pytest.param("廃棄物処理法", "9", "1", "", id="廃棄物処理法_art9_p1"),
    pytest.param("廃棄物処理法", "15", "1", "", id="廃棄物処理法_art15_p1"),
    pytest.param("廃棄物処理法", "15_2", "", "", id="廃棄物処理法_art15_2"),
    pytest.param("廃棄物処理法", "9", "5", "", id="廃棄物処理法_art9_p5"),
    pytest.param("廃棄物処理法", "9_3", "", "", id="廃棄物処理法_art9_3"),
    pytest.param("廃棄物処理法", "14_3", "", "", id="廃棄物処理法_art14_3"),
    pytest.param("廃棄物処理法", "14_6", "", "", id="廃棄物処理法_art14_6"),
    pytest.param("廃棄物処理法施行規則", "8", "", "8", id="廃棄物処理法施行規則_art8_i8"),
    pytest.param("廃棄物処理法", "19", "1", "", id="廃棄物処理法_art19_p1"),
    pytest.param("廃棄物処理法", "17_2", "3", "", id="廃棄物処理法_art17_2_p3"),
    pytest.param("廃棄物処理法", "8", "4", "", id="廃棄物処理法_art8_p4"),
    pytest.param("廃棄物処理法", "9", "", "", id="廃棄物処理法_art9"),
    pytest.param("廃棄物処理法", "9_3", "2", "", id="廃棄物処理法_art9_3_p2"),
    pytest.param("廃棄物処理法", "9_3", "9", "", id="廃棄物処理法_art9_3_p9"),
    pytest.param("廃棄物処理法", "9_3", "7", "", id="廃棄物処理法_art9_3_p7"),
    pytest.param("廃棄物処理法施行規則", "3", "5", "", id="廃棄物処理法施行規則_art3_p5"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "8", id="廃棄物処理法施行規則_art9_3_i8"),
    pytest.param("廃棄物処理法", "6_2", "6", "", id="廃棄物処理法_art6_2_p6"),
    pytest.param("廃棄物処理法", "12_3", "1", "", id="廃棄物処理法_art12_3_p1"),
    pytest.param("廃棄物処理法", "16_2", "", "", id="廃棄物処理法_art16_2"),
    pytest.param("廃棄物処理法施行令", "14", "", "", id="廃棄物処理法施行令_art14"),
    pytest.param("廃棄物処理法", "16_2", "", "3", id="廃棄物処理法_art16_2_i3"),
    pytest.param("廃棄物処理法", "19_4", "", "", id="廃棄物処理法_art19_4"),
    pytest.param("廃棄物処理法", "8", "2", "4", id="廃棄物処理法_art8_p2_i4"),
    pytest.param("廃棄物処理法", "9_3", "8", "", id="廃棄物処理法_art9_3_p8"),
    pytest.param("廃棄物処理法施行規則", "5_2", "", "", id="廃棄物処理法施行規則_art5_2"),
    pytest.param("廃棄物処理法施行令", "6_5", "", "", id="廃棄物処理法施行令_art6_5"),
    pytest.param("廃棄物処理法", "1", "2", "", id="廃棄物処理法_art1_p2"),
    pytest.param("廃棄物処理法", "19", "", "", id="廃棄物処理法_art19"),
    pytest.param("廃棄物処理法施行令", "6", "", "", id="廃棄物処理法施行令_art6"),
    pytest.param("廃棄物処理法施行規則", "7_2", "", "", id="廃棄物処理法施行規則_art7_2"),
    pytest.param("廃棄物処理法", "12_7", "1", "", id="廃棄物処理法_art12_7_p1"),
    pytest.param("廃棄物処理法", "24_2", "1", "", id="廃棄物処理法_art24_2_p1"),
    pytest.param("廃棄物処理法", "2", "5", "", id="廃棄物処理法_art2_p5"),
    pytest.param("廃棄物処理法", "23_3", "1", "", id="廃棄物処理法_art23_3_p1"),
    pytest.param("廃棄物処理法施行令", "4_6", "", "", id="廃棄物処理法施行令_art4_6"),
    pytest.param("廃棄物処理法施行令", "6", "1", "3", id="廃棄物処理法施行令_art6_p1_i3"),
    pytest.param("廃棄物処理法施行令", "7", "", "", id="廃棄物処理法施行令_art7"),
    pytest.param("廃棄物処理法施行令", "2_4", "", "", id="廃棄物処理法施行令_art2_4"),
    pytest.param("廃棄物処理法", "23_5", "", "", id="廃棄物処理法_art23_5"),
    pytest.param("廃棄物処理法", "14", "5", "2", id="廃棄物処理法_art14_p5_i2"),
    pytest.param("廃棄物処理法", "7", "5", "4", id="廃棄物処理法_art7_p5_i4"),
    pytest.param("廃棄物処理法", "14_4", "5", "2", id="廃棄物処理法_art14_4_p5_i2"),
    pytest.param("廃棄物処理法", "14", "", "", id="廃棄物処理法_art14"),
    pytest.param("廃棄物処理法", "14", "11", "", id="廃棄物処理法_art14_p11"),
    pytest.param("廃棄物処理法", "14", "1", "", id="廃棄物処理法_art14_p1"),
    pytest.param("廃棄物処理法", "14", "6", "", id="廃棄物処理法_art14_p6"),
    pytest.param("廃棄物処理法", "14_2", "1", "", id="廃棄物処理法_art14_2_p1"),
    pytest.param("廃棄物処理法", "14_4", "1", "", id="廃棄物処理法_art14_4_p1"),
    pytest.param("廃棄物処理法", "14_4", "6", "", id="廃棄物処理法_art14_4_p6"),
    pytest.param("廃棄物処理法", "14_5", "1", "", id="廃棄物処理法_art14_5_p1"),
    pytest.param("廃棄物処理法", "14_4", "4", "", id="廃棄物処理法_art14_4_p4"),
    pytest.param("廃棄物処理法", "15_4", "", "", id="廃棄物処理法_art15_4"),
    pytest.param("廃棄物処理法", "9_6", "1", "", id="廃棄物処理法_art9_6_p1"),
    pytest.param("廃棄物処理法", "9_7", "2", "", id="廃棄物処理法_art9_7_p2"),
    pytest.param("廃棄物処理法", "14", "3", "", id="廃棄物処理法_art14_p3"),
    pytest.param("廃棄物処理法", "14", "2", "", id="廃棄物処理法_art14_p2"),
    pytest.param("廃棄物処理法", "14_4", "2", "", id="廃棄物処理法_art14_4_p2"),
    pytest.param("廃棄物処理法", "20_2", "", "", id="廃棄物処理法_art20_2"),
    pytest.param("廃棄物処理法", "21_3", "1", "", id="廃棄物処理法_art21_3_p1"),
    pytest.param("廃棄物処理法", "15", "2", "", id="廃棄物処理法_art15_p2"),
    pytest.param("廃棄物処理法", "15_2", "1", "", id="廃棄物処理法_art15_2_p1"),
    pytest.param("廃棄物処理法", "15_2", "4", "", id="廃棄物処理法_art15_2_p4"),
    pytest.param("廃棄物処理法", "15_3", "", "", id="廃棄物処理法_art15_3"),
    pytest.param("廃棄物処理法", "9_5", "1", "", id="廃棄物処理法_art9_5_p1"),
    pytest.param("廃棄物処理法", "12_7", "3", "", id="廃棄物処理法_art12_7_p3"),
    pytest.param("廃棄物処理法", "12_7", "4", "", id="廃棄物処理法_art12_7_p4"),
    pytest.param("廃棄物処理法", "23_3", "", "", id="廃棄物処理法_art23_3"),
    pytest.param("廃棄物処理法", "12_7", "7", "", id="廃棄物処理法_art12_7_p7"),
    pytest.param("廃棄物処理法", "21_3", "", "", id="廃棄物処理法_art21_3"),
    pytest.param("廃棄物処理法施行規則", "9_2", "2", "9", id="廃棄物処理法施行規則_art9_2_p2_i9"),
    pytest.param("廃棄物処理法施行規則", "10_4", "2", "8", id="廃棄物処理法施行規則_art10_4_p2_i8"),
    pytest.param("廃棄物処理法施行規則", "10_12", "2", "", id="廃棄物処理法施行規則_art10_12_p2"),
    pytest.param("廃棄物処理法施行規則", "9_2", "2", "", id="廃棄物処理法施行規則_art9_2_p2"),
    pytest.param("廃棄物処理法施行規則", "10_16", "2", "", id="廃棄物処理法施行規則_art10_16_p2"),
    pytest.param("廃棄物処理法施行規則", "10_22", "2", "", id="廃棄物処理法施行規則_art10_22_p2"),
    pytest.param("廃棄物処理法施行規則", "10_22", "3", "", id="廃棄物処理法施行規則_art10_22_p3"),
    pytest.param("廃棄物処理法施行規則", "11", "6", "", id="廃棄物処理法施行規則_art11_p6"),
    pytest.param("廃棄物処理法施行規則", "12_9", "3", "7", id="廃棄物処理法施行規則_art12_9_p3_i7"),
    pytest.param("廃棄物処理法施行規則", "11", "6", "10", id="廃棄物処理法施行規則_art11_p6_i10"),
    pytest.param("廃棄物処理法施行規則", "12_11", "", "", id="廃棄物処理法施行規則_art12_11"),
    pytest.param("廃棄物処理法施行規則", "12_12", "2", "2", id="廃棄物処理法施行規則_art12_12_p2_i2"),
    pytest.param("廃棄物処理法施行規則", "9_2", "2", "1", id="廃棄物処理法施行規則_art9_2_p2_i1"),
    pytest.param("廃棄物処理法施行規則", "11", "2", "", id="廃棄物処理法施行規則_art11_p2"),
    pytest.param("廃棄物処理法施行規則", "11", "3", "", id="廃棄物処理法施行規則_art11_p3"),
    pytest.param("廃棄物処理法施行規則", "11", "5", "3", id="廃棄物処理法施行規則_art11_p5_i3"),
    pytest.param("廃棄物処理法施行規則", "11", "5", "4", id="廃棄物処理法施行規則_art11_p5_i4"),
    pytest.param("廃棄物処理法施行規則", "11_2", "", "", id="廃棄物処理法施行規則_art11_2"),
    pytest.param("廃棄物処理法施行規則", "8_38", "", "", id="廃棄物処理法施行規則_art8_38"),
    pytest.param("廃棄物処理法施行令", "2", "", "8", id="廃棄物処理法施行令_art2_i8"),
    pytest.param("廃棄物処理法", "6_2", "2", "", id="廃棄物処理法_art6_2_p2"),
    pytest.param("廃棄物処理法", "5_5", "", "", id="廃棄物処理法_art5_5"),
    pytest.param("廃棄物処理法施行規則", "1_2", "5", "", id="廃棄物処理法施行規則_art1_2_p5"),
    pytest.param("廃棄物処理法施行令", "2_4", "", "5", id="廃棄物処理法施行令_art2_4_i5"),
    pytest.param("廃棄物処理法施行令", "6_7", "", "", id="廃棄物処理法施行令_art6_7"),
    pytest.param("廃棄物処理法施行令", "6_4", "", "", id="廃棄物処理法施行令_art6_4"),
    pytest.param("廃棄物処理法施行令", "27", "1", "", id="廃棄物処理法施行令_art27_p1"),
    pytest.param("廃棄物処理法施行令", "16_2", "", "", id="廃棄物処理法施行令_art16_2"),
    pytest.param("廃棄物処理法施行令", "16_3", "", "1", id="廃棄物処理法施行令_art16_3_i1"),
    pytest.param("廃棄物処理法", "12_7", "5", "", id="廃棄物処理法_art12_7_p5"),
    pytest.param("廃棄物処理法", "12", "", "", id="廃棄物処理法_art12"),
    pytest.param("廃棄物処理法", "14_2", "4", "", id="廃棄物処理法_art14_2_p4"),
    pytest.param("廃棄物処理法", "25", "1", "5", id="廃棄物処理法_art25_p1_i5"),
    pytest.param("廃棄物処理法", "26", "", "2", id="廃棄物処理法_art26_i2"),
    pytest.param("廃棄物処理法", "17_2", "", "", id="廃棄物処理法_art17_2"),
    pytest.param("廃棄物処理法", "9_10", "1", "", id="廃棄物処理法_art9_10_p1"),
    pytest.param("廃棄物処理法施行規則", "8_31", "", "", id="廃棄物処理法施行規則_art8_31"),
    pytest.param("廃棄物処理法施行規則", "8_21", "", "", id="廃棄物処理法施行規則_art8_21"),
    pytest.param("廃棄物処理法施行規則", "8_5", "1", "", id="廃棄物処理法施行規則_art8_5_p1"),
    pytest.param("廃棄物処理法施行規則", "8_2", "", "", id="廃棄物処理法施行規則_art8_2"),
    pytest.param("廃棄物処理法施行規則", "7", "", "", id="廃棄物処理法施行規則_art7"),
    pytest.param("廃棄物処理法施行規則", "13", "", "", id="廃棄物処理法施行規則_art13"),
    pytest.param("廃棄物処理法施行規則", "13_3", "2", "4", id="廃棄物処理法施行規則_art13_3_p2_i4"),
    pytest.param("廃棄物処理法施行規則", "6_6", "", "", id="廃棄物処理法施行規則_art6_6"),
    pytest.param("廃棄物処理法施行令", "3", "", "", id="廃棄物処理法施行令_art3"),
    pytest.param("廃棄物処理法施行令", "7", "", "14", id="廃棄物処理法施行令_art7_i14"),
    pytest.param("廃棄物処理法施行令", "27", "", "", id="廃棄物処理法施行令_art27"),
    pytest.param("廃棄物処理法施行令", "7_2", "", "", id="廃棄物処理法施行令_art7_2"),
    pytest.param("廃棄物処理法施行令", "6_5", "1", "", id="廃棄物処理法施行令_art6_5_p1"),
    pytest.param("廃棄物処理法施行規則", "1_7", "", "", id="廃棄物処理法施行規則_art1_7"),
    pytest.param("廃棄物処理法施行規則", "10_4", "", "", id="廃棄物処理法施行規則_art10_4"),
    pytest.param("廃棄物処理法施行規則", "7_8", "", "", id="廃棄物処理法施行規則_art7_8"),
    pytest.param("廃棄物処理法施行規則", "5_5", "", "", id="廃棄物処理法施行規則_art5_5"),
    pytest.param("廃棄物処理法施行規則", "7_3", "", "", id="廃棄物処理法施行規則_art7_3"),
    pytest.param("廃棄物処理法施行規則", "7_5", "", "", id="廃棄物処理法施行規則_art7_5"),
    pytest.param("廃棄物処理法施行規則", "8_4", "", "", id="廃棄物処理法施行規則_art8_4"),
    pytest.param("廃棄物処理法施行規則", "8_5", "", "", id="廃棄物処理法施行規則_art8_5"),
    pytest.param("廃棄物処理法施行規則", "9_2", "", "", id="廃棄物処理法施行規則_art9_2"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "", id="廃棄物処理法施行規則_art9_3"),
    pytest.param("廃棄物処理法施行規則", "12", "", "", id="廃棄物処理法施行規則_art12"),
    pytest.param("廃棄物処理法施行規則", "1_5", "", "", id="廃棄物処理法施行規則_art1_5"),
    pytest.param("廃棄物処理法施行規則", "2_5", "", "", id="廃棄物処理法施行規則_art2_5"),
    pytest.param("廃棄物処理法施行規則", "6", "", "", id="廃棄物処理法施行規則_art6"),
    pytest.param("廃棄物処理法施行規則", "1_9", "", "", id="廃棄物処理法施行規則_art1_9"),
    pytest.param("廃棄物処理法施行規則", "8_6", "", "", id="廃棄物処理法施行規則_art8_6"),
    pytest.param("廃棄物処理法施行規則", "10", "", "", id="廃棄物処理法施行規則_art10"),
    pytest.param("廃棄物処理法施行規則", "4_5", "", "", id="廃棄物処理法施行規則_art4_5"),
    pytest.param("廃棄物処理法施行規則", "4_8", "", "", id="廃棄物処理法施行規則_art4_8"),
    pytest.param("廃棄物処理法施行規則", "1_2", "5", "2", id="廃棄物処理法施行規則_art1_2_p5_i2"),
    pytest.param("廃棄物処理法施行令", "6", "1", "4", id="廃棄物処理法施行令_art6_p1_i4"),
    pytest.param("廃棄物処理法", "2", "4", "1", id="廃棄物処理法_art2_p4_i1"),
    pytest.param("廃棄物処理法施行規則", "9", "", "2", id="廃棄物処理法施行規則_art9_i2"),
    pytest.param("廃棄物処理法施行令", "4_2", "", "1", id="廃棄物処理法施行令_art4_2_i1"),
    pytest.param("廃棄物処理法施行令", "6_5", "1", "3", id="廃棄物処理法施行令_art6_5_p1_i3"),
    pytest.param("廃棄物処理法施行令", "7", "", "8", id="廃棄物処理法施行令_art7_i8"),
    pytest.param("廃棄物処理法施行令", "6_10", "", "", id="廃棄物処理法施行令_art6_10"),
    pytest.param("廃棄物処理法施行令", "7", "", "3", id="廃棄物処理法施行令_art7_i3"),
    pytest.param("廃棄物処理法施行令", "7", "", "4", id="廃棄物処理法施行令_art7_i4"),
    pytest.param("廃棄物処理法施行令", "7", "", "11", id="廃棄物処理法施行令_art7_i11"),
    pytest.param("廃棄物処理法", "15_2", "1", "1", id="廃棄物処理法_art15_2_p1_i1"),
    pytest.param("廃棄物処理法", "12", "2", "", id="廃棄物処理法_art12_p2"),
    pytest.param("廃棄物処理法", "15_2", "1", "2", id="廃棄物処理法_art15_2_p1_i2"),
    pytest.param("廃棄物処理法", "15", "3", "", id="廃棄物処理法_art15_p3"),
    pytest.param("廃棄物処理法施行規則", "12", "", "1", id="廃棄物処理法施行規則_art12_i1"),
    pytest.param("廃棄物処理法施行規則", "12", "", "4", id="廃棄物処理法施行規則_art12_i4"),
    pytest.param("廃棄物処理法施行規則", "12", "", "6", id="廃棄物処理法施行規則_art12_i6"),
    pytest.param("廃棄物処理法施行規則", "12", "", "7", id="廃棄物処理法施行規則_art12_i7"),
    pytest.param("廃棄物処理法施行規則", "12_2", "9", "1", id="廃棄物処理法施行規則_art12_2_p9_i1"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "", id="廃棄物処理法施行規則_art12_6"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "1", id="廃棄物処理法施行規則_art12_6_i1"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "3", id="廃棄物処理法施行規則_art12_6_i3"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "4", id="廃棄物処理法施行規則_art12_6_i4"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "5", id="廃棄物処理法施行規則_art12_6_i5"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "7", id="廃棄物処理法施行規則_art12_6_i7"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "8", id="廃棄物処理法施行規則_art12_6_i8"),
    pytest.param("廃棄物処理法施行規則", "12_6", "", "9", id="廃棄物処理法施行規則_art12_6_i9"),
    pytest.param("廃棄物処理法施行規則", "12_7", "9", "1", id="廃棄物処理法施行規則_art12_7_p9_i1"),
    pytest.param("廃棄物処理法施行規則", "11", "", "", id="廃棄物処理法施行規則_art11"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "1", id="廃棄物処理法施行規則_art9_3_i1"),
    pytest.param("廃棄物処理法施行規則", "12_8", "", "", id="廃棄物処理法施行規則_art12_8"),
    pytest.param("廃棄物処理法", "12", "7", "", id="廃棄物処理法_art12_p7"),
    pytest.param("廃棄物処理法", "12_2", "5", "", id="廃棄物処理法_art12_2_p5"),
    pytest.param("廃棄物処理法施行令", "6", "1", "", id="廃棄物処理法施行令_art6_p1"),
    pytest.param("廃棄物処理法施行令", "2", "", "7", id="廃棄物処理法施行令_art2_i7"),
    pytest.param("廃棄物処理法施行規則", "12_7", "", "", id="廃棄物処理法施行規則_art12_7"),
    pytest.param("廃棄物処理法施行令", "3_3", "", "", id="廃棄物処理法施行令_art3_3"),
    pytest.param("廃棄物処理法施行令", "6_6", "", "", id="廃棄物処理法施行令_art6_6"),
    pytest.param("廃棄物処理法施行令", "6_2", "", "", id="廃棄物処理法施行令_art6_2"),
    pytest.param("廃棄物処理法施行令", "6_6", "", "1", id="廃棄物処理法施行令_art6_6_i1"),
    pytest.param("廃棄物処理法施行令", "6", "", "23", id="廃棄物処理法施行令_art6_i23"),
    pytest.param("廃棄物処理法施行令", "22", "1", "3", id="廃棄物処理法施行令_art22_p1_i3"),
    pytest.param("廃棄物処理法施行令", "6_5", "1", "1", id="廃棄物処理法施行令_art6_5_p1_i1"),
    pytest.param("廃棄物処理法施行令", "6", "1", "1", id="廃棄物処理法施行令_art6_p1_i1"),
    pytest.param("廃棄物処理法", "2", "11", "", id="廃棄物処理法_art2_p11"),
    pytest.param("廃棄物処理法", "12_2", "8", "", id="廃棄物処理法_art12_2_p8"),
    pytest.param("廃棄物処理法", "12", "9", "", id="廃棄物処理法_art12_p9"),
    pytest.param("廃棄物処理法", "12_2", "10", "", id="廃棄物処理法_art12_2_p10"),
    pytest.param("廃棄物処理法", "12_2", "1", "", id="廃棄物処理法_art12_2_p1"),
    pytest.param("廃棄物処理法", "12", "1", "", id="廃棄物処理法_art12_p1"),
    pytest.param("廃棄物処理法", "12_2", "", "", id="廃棄物処理法_art12_2"),
    pytest.param("廃棄物処理法", "12_2", "6", "", id="廃棄物処理法_art12_2_p6"),
    pytest.param("廃棄物処理法", "12_2", "2", "", id="廃棄物処理法_art12_2_p2"),
    pytest.param("廃棄物処理法", "12_3", "6", "", id="廃棄物処理法_art12_3_p6"),
    pytest.param("廃棄物処理法", "12_3", "8", "", id="廃棄物処理法_art12_3_p8"),
    pytest.param("廃棄物処理法", "12_2", "14", "", id="廃棄物処理法_art12_2_p14"),
    pytest.param("廃棄物処理法", "7", "15", "", id="廃棄物処理法_art7_p15"),
    pytest.param("廃棄物処理法", "12", "13", "", id="廃棄物処理法_art12_p13"),
    pytest.param("廃棄物処理法", "7", "2", "", id="廃棄物処理法_art7_p2"),
    pytest.param("廃棄物処理法施行規則", "1_2", "7", "", id="廃棄物処理法施行規則_art1_2_p7"),
    pytest.param("廃棄物処理法施行規則", "1_3", "", "", id="廃棄物処理法施行規則_art1_3"),
    pytest.param("廃棄物処理法施行規則", "3", "", "", id="廃棄物処理法施行規則_art3"),
    pytest.param("廃棄物処理法施行規則", "8_3", "", "", id="廃棄物処理法施行規則_art8_3"),
    pytest.param("廃棄物処理法施行規則", "8_16", "", "", id="廃棄物処理法施行規則_art8_16"),
    pytest.param("廃棄物処理法施行規則", "8", "", "1", id="廃棄物処理法施行規則_art8_i1"),
    pytest.param("廃棄物処理法施行規則", "8", "", "2", id="廃棄物処理法施行規則_art8_i2"),
    pytest.param("廃棄物処理法施行規則", "8", "", "3", id="廃棄物処理法施行規則_art8_i3"),
    pytest.param("廃棄物処理法施行規則", "8", "", "4", id="廃棄物処理法施行規則_art8_i4"),
    pytest.param("廃棄物処理法施行規則", "8_13", "", "5", id="廃棄物処理法施行規則_art8_13_i5"),
    pytest.param("廃棄物処理法施行規則", "1_10", "", "", id="廃棄物処理法施行規則_art1_10"),
    pytest.param("廃棄物処理法施行規則", "8_28", "", "", id="廃棄物処理法施行規則_art8_28"),
    pytest.param("廃棄物処理法施行規則", "8_20", "", "", id="廃棄物処理法施行規則_art8_20"),
    pytest.param("廃棄物処理法施行規則", "8_22", "", "", id="廃棄物処理法施行規則_art8_22"),
    pytest.param("廃棄物処理法施行規則", "8_24", "", "", id="廃棄物処理法施行規則_art8_24"),
    pytest.param("廃棄物処理法施行規則", "8_27", "", "", id="廃棄物処理法施行規則_art8_27"),
    pytest.param("廃棄物処理法施行規則", "8_30", "", "", id="廃棄物処理法施行規則_art8_30"),
    pytest.param("廃棄物処理法施行規則", "8_18", "", "", id="廃棄物処理法施行規則_art8_18"),
    pytest.param("廃棄物処理法施行規則", "8_18", "3", "", id="廃棄物処理法施行規則_art8_18_p3"),
    pytest.param("廃棄物処理法", "13_2", "", "", id="廃棄物処理法_art13_2"),
    pytest.param("廃棄物処理法", "21_3", "3", "", id="廃棄物処理法_art21_3_p3"),
    pytest.param("廃棄物処理法", "21_3", "2", "", id="廃棄物処理法_art21_3_p2"),
    pytest.param("廃棄物処理法", "21_3", "4", "", id="廃棄物処理法_art21_3_p4"),
    pytest.param("廃棄物処理法", "6", "2", "", id="廃棄物処理法_art6_p2"),
    pytest.param("廃棄物処理法", "12", "10", "", id="廃棄物処理法_art12_p10"),
    pytest.param("廃棄物処理法", "12_2", "11", "", id="廃棄物処理法_art12_2_p11"),
    pytest.param("廃棄物処理法施行令", "6_11", "", "2", id="廃棄物処理法施行令_art6_11_i2"),
    pytest.param("廃棄物処理法施行令", "6_14", "", "2", id="廃棄物処理法施行令_art6_14_i2"),
    pytest.param("廃棄物処理法", "33", "", "", id="廃棄物処理法_art33"),
    pytest.param("廃棄物処理法", "12_2", "12", "", id="廃棄物処理法_art12_2_p12"),
    pytest.param("廃棄物処理法", "12_3", "3", "", id="廃棄物処理法_art12_3_p3"),
    pytest.param("廃棄物処理法", "14", "13", "", id="廃棄物処理法_art14_p13"),
    pytest.param("廃棄物処理法", "12_4", "", "", id="廃棄物処理法_art12_4"),
    pytest.param("廃棄物処理法施行規則", "8_19", "", "", id="廃棄物処理法施行規則_art8_19"),
    pytest.param("廃棄物処理法施行令", "6_2", "", "3", id="廃棄物処理法施行令_art6_2_i3"),
    pytest.param("廃棄物処理法施行令", "6_12", "", "3", id="廃棄物処理法施行令_art6_12_i3"),
    pytest.param("廃棄物処理法施行令", "6_2", "", "4", id="廃棄物処理法施行令_art6_2_i4"),
    pytest.param("廃棄物処理法", "7_4", "1", "", id="廃棄物処理法_art7_4_p1"),
    pytest.param("廃棄物処理法", "7", "5", "", id="廃棄物処理法_art7_p5"),
    pytest.param("廃棄物処理法", "8_2", "1", "1", id="廃棄物処理法_art8_2_p1_i1"),
    pytest.param("廃棄物処理法", "8_2", "", "", id="廃棄物処理法_art8_2"),
    pytest.param("廃棄物処理法", "30", "", "3", id="廃棄物処理法_art30_i3"),
    pytest.param("廃棄物処理法", "9_2", "1", "3", id="廃棄物処理法_art9_2_p1_i3"),
    pytest.param("廃棄物処理法", "9_2", "1", "", id="廃棄物処理法_art9_2_p1"),
    pytest.param("廃棄物処理法", "8_4", "", "", id="廃棄物処理法_art8_4"),
    pytest.param("廃棄物処理法", "9_2", "", "", id="廃棄物処理法_art9_2"),
    pytest.param("廃棄物処理法", "8_5", "6", "", id="廃棄物処理法_art8_5_p6"),
    pytest.param("廃棄物処理法", "19_7", "", "", id="廃棄物処理法_art19_7"),
    pytest.param("廃棄物処理法", "19_7", "6", "", id="廃棄物処理法_art19_7_p6"),
    pytest.param("廃棄物処理法", "12", "4", "", id="廃棄物処理法_art12_p4"),
    pytest.param("廃棄物処理法", "13_2", "1", "", id="廃棄物処理法_art13_2_p1"),
    pytest.param("廃棄物処理法", "7_3", "", "", id="廃棄物処理法_art7_3"),
    pytest.param("廃棄物処理法", "9_8", "9", "", id="廃棄物処理法_art9_8_p9"),
    pytest.param("廃棄物処理法", "9_9", "10", "", id="廃棄物処理法_art9_9_p10"),
    pytest.param("廃棄物処理法", "9_10", "7", "", id="廃棄物処理法_art9_10_p7"),
    pytest.param("廃棄物処理法", "19_3", "", "", id="廃棄物処理法_art19_3"),
    pytest.param("廃棄物処理法", "19_4", "1", "", id="廃棄物処理法_art19_4_p1"),
    pytest.param("廃棄物処理法", "15_3", "1", "", id="廃棄物処理法_art15_3_p1"),
    pytest.param("廃棄物処理法", "12_3", "2", "", id="廃棄物処理法_art12_3_p2"),
    pytest.param("廃棄物処理法", "13_13", "", "", id="廃棄物処理法_art13_13"),
    pytest.param("廃棄物処理法", "19_5", "1", "5", id="廃棄物処理法_art19_5_p1_i5"),
    pytest.param("廃棄物処理法", "2", "12", "", id="廃棄物処理法_art2_p12"),
    pytest.param("廃棄物処理法", "18_14", "", "", id="廃棄物処理法_art18_14"),
    pytest.param("廃棄物処理法", "19_5", "", "", id="廃棄物処理法_art19_5"),
    pytest.param("廃棄物処理法", "19_8", "", "", id="廃棄物処理法_art19_8"),
    pytest.param("廃棄物処理法", "21_2", "1", "", id="廃棄物処理法_art21_2_p1"),
    pytest.param("廃棄物処理法施行規則", "4_4", "", "", id="廃棄物処理法施行規則_art4_4"),
    pytest.param("廃棄物処理法施行規則", "4_15", "", "", id="廃棄物処理法施行規則_art4_15"),
    pytest.param("廃棄物処理法施行規則", "4", "", "", id="廃棄物処理法施行規則_art4"),
    pytest.param("廃棄物処理法施行規則", "5", "", "", id="廃棄物処理法施行規則_art5"),
    pytest.param("廃棄物処理法施行規則", "8_20", "", "6", id="廃棄物処理法施行規則_art8_20_i6"),
    pytest.param("廃棄物処理法施行規則", "9_2", "2", "15", id="廃棄物処理法施行規則_art9_2_p2_i15"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "2", id="廃棄物処理法施行規則_art9_3_i2"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "3", id="廃棄物処理法施行規則_art9_3_i3"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "4", id="廃棄物処理法施行規則_art9_3_i4"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "5", id="廃棄物処理法施行規則_art9_3_i5"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "6", id="廃棄物処理法施行規則_art9_3_i6"),
    pytest.param("廃棄物処理法施行規則", "9_3", "", "7", id="廃棄物処理法施行規則_art9_3_i7"),
    pytest.param("廃棄物処理法施行規則", "9_2", "3", "2", id="廃棄物処理法施行規則_art9_2_p3_i2"),
    pytest.param("廃棄物処理法施行規則", "9_2", "3", "", id="廃棄物処理法施行規則_art9_2_p3"),
    pytest.param("廃棄物処理法施行規則", "10_6", "", "", id="廃棄物処理法施行規則_art10_6"),
    pytest.param("廃棄物処理法施行規則", "18_2", "", "", id="廃棄物処理法施行規則_art18_2"),
    pytest.param("廃棄物処理法施行規則", "7_2", "3", "", id="廃棄物処理法施行規則_art7_2_p3"),
    pytest.param("廃棄物処理法施行規則", "8_16", "", "1", id="廃棄物処理法施行規則_art8_16_i1"),
    pytest.param("廃棄物処理法施行規則", "10_10", "", "", id="廃棄物処理法施行規則_art10_10"),
    pytest.param("廃棄物処理法施行規則", "6_19", "", "", id="廃棄物処理法施行規則_art6_19"),
    pytest.param("廃棄物処理法", "8_3", "2", "", id="廃棄物処理法_art8_3_p2"),
    pytest.param("廃棄物処理法", "9_8", "6", "", id="廃棄物処理法_art9_8_p6"),
    pytest.param("廃棄物処理法", "18", "1", "", id="廃棄物処理法_art18_p1"),
    pytest.param("廃棄物処理法", "12", "3", "", id="廃棄物処理法_art12_p3"),
    pytest.param("廃棄物処理法", "12_4", "2", "", id="廃棄物処理法_art12_4_p2"),
    pytest.param("廃棄物処理法", "21", "", "", id="廃棄物処理法_art21"),
    pytest.param("廃棄物処理法", "32", "2", "", id="廃棄物処理法_art32_p2"),
    pytest.param("廃棄物処理法", "33", "", "2", id="廃棄物処理法_art33_i2"),
    pytest.param("廃棄物処理法施行令", "3", "", "2", id="廃棄物処理法施行令_art3_i2"),
    pytest.param("廃棄物処理法施行令", "6", "1", "2", id="廃棄物処理法施行令_art6_p1_i2"),
    pytest.param("廃棄物処理法", "11", "2", "", id="廃棄物処理法_art11_p2"),
    pytest.param("廃棄物処理法", "15_19", "", "", id="廃棄物処理法_art15_19"),
    pytest.param("廃棄物処理法", "15_18", "", "", id="廃棄物処理法_art15_18"),
    pytest.param("廃棄物処理法施行規則", "12_7", "13", "", id="廃棄物処理法施行規則_art12_7_p13"),
    pytest.param("廃棄物処理法施行規則", "12_2", "13", "", id="廃棄物処理法施行規則_art12_2_p13"),
    pytest.param("廃棄物処理法施行規則", "2", "", "", id="廃棄物処理法施行規則_art2"),
    pytest.param("廃棄物処理法施行規則", "5_6", "", "", id="廃棄物処理法施行規則_art5_6"),
    pytest.param("廃棄物処理法施行規則", "12_34", "", "", id="廃棄物処理法施行規則_art12_34"),
    pytest.param("廃棄物処理法", "14_4", "", "", id="廃棄物処理法_art14_4"),
    pytest.param("廃棄物処理法", "28", "1", "", id="廃棄物処理法_art28_p1"),
    pytest.param("廃棄物処理法", "24", "1", "", id="廃棄物処理法_art24_p1"),
    pytest.param("廃棄物処理法", "28", "", "", id="廃棄物処理法_art28"),
    pytest.param("廃棄物処理法施行規則", "2", "1", "4", id="廃棄物処理法施行規則_art2_p1_i4"),
    pytest.param("廃棄物処理法施行規則", "3", "2", "", id="廃棄物処理法施行規則_art3_p2"),
    pytest.param("廃棄物処理法施行規則", "2", "1", "1", id="廃棄物処理法施行規則_art2_p1_i1"),
]


@pytest.mark.integration
@pytest.mark.parametrize("law,article,paragraph,item", ENV_PDF_PARAMS)
def test_env_pdf_law_ref(law, article, paragraph, item):
    """Test that a law article referenced in env.go.jp PDFs can be retrieved."""
    result = asyncio.run(_find_article(law, article, paragraph or None, item or None))
    assert "error" not in result, f"Error looking up {law} art.{article}: {result.get('error')}"
    assert result.get("matches_found", 0) > 0, (
        f"No matches for {law} art.{article}"
        + (f" p.{paragraph}" if paragraph else "")
        + (f" i.{item}" if item else "")
    )
